services:
  app:
    build:
      context: app
      dockerfile: ../docker/app.Dockerfile
      args:
        NODE_ENV: production
    image: ${APP_IMAGE}:${IMAGE_TAG}
    environment:
      NODE_ENV: production
      APP_PORT: 3000

  portal:
    build:
      context: portal
      dockerfile: ../docker/portal.Dockerfile
    image: ${PORTAL_IMAGE}:${IMAGE_TAG}
    environment:
      NODE_ENV: production
      PORT: 3001

  freeswitch:
    image: ${FREESWITCH_REMOTE_IMAGE:-docker.io/your-dockerhub-user/freeswitch}:${FREESWITCH_REMOTE_TAG:-latest}
    environment:
      TZ: ${TIMEZONE:-Asia/Ho_Chi_Minh}
