# version: "3.9"
services:
  app:
    image: node:20-slim
    container_name: fs-xml-app
    working_dir: /app
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - APP_PORT=${APP_PORT:-3000}
      - TZ=${TIMEZONE:-Asia/Ho_Chi_Minh}
      - DB_HOST=${DB_HOST:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-fsapp}
      - DB_PASSWORD=${DB_PASSWORD:-fsapp}
      - DB_NAME=${DB_NAME:-freeswitch}
      - DB_LOGGING=${DB_LOGGING:-false}
      - DB_SYNC=${DB_SYNC:-true}
      - SEED_DEMO_DATA=${SEED_DEMO_DATA:-true}
      - FS_ESL_HOST=${FS_ESL_HOST:-127.0.0.1}
      - FS_ESL_PORT=${FS_ESL_PORT:-8021}
      - FS_ESL_PASSWORD=${FS_ESL_PASSWORD:-ClueCon}
      - RECORDINGS_DIR=${RECORDINGS_DIR:-/recordings}
    entrypoint: ["/usr/local/bin/app-entrypoint.sh"]
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - app-node-modules:/app/node_modules
      - ./docker/app-entrypoint.sh:/usr/local/bin/app-entrypoint.sh:ro
      - ./data/recordings:/recordings:ro
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "node -e \"fetch('http://localhost:3000/health').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))\""]
      interval: 10s
      timeout: 3s
      retries: 10

  freeswitch:
    # platform: linux/amd64
    build:
      context: .
      dockerfile: docker/freeswitch.Dockerfile
      args:
        - FS_TOKEN=${FS_TOKEN}
    container_name: freeswitch-core
    depends_on:
      app:
        condition: service_healthy
    environment:
      - TZ=${TIMEZONE:-Asia/Ho_Chi_Minh}
      - EXT_SIP_IP=${EXT_SIP_IP:-auto}
      - EXT_RTP_IP=${EXT_RTP_IP:-auto}
      - CDR_HTTP_HEADERS=${CDR_HTTP_HEADERS:-}
    network_mode: host
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      nice: -20
    volumes:
      # Mount only specific config files to avoid shadowing defaults
      - ./freeswitch/conf/autoload_configs/event_socket.conf.xml:/etc/freeswitch/autoload_configs/event_socket.conf.xml
      - ./freeswitch/conf/autoload_configs/xml_curl.conf.xml:/etc/freeswitch/autoload_configs/xml_curl.conf.xml
      - ./freeswitch/conf/autoload_configs/xml_cdr.conf.xml:/etc/freeswitch/autoload_configs/xml_cdr.conf.xml
      - ./freeswitch/conf/autoload_configs/modules.conf.xml:/etc/freeswitch/autoload_configs/modules.conf.xml
      - ./freeswitch/conf/vars_local.xml:/etc/freeswitch/vars_local.xml
      - ./freeswitch/conf/sip_profiles/internal.xml:/etc/freeswitch/sip_profiles/internal.xml
      - ./docker/fs-entrypoint.sh:/usr/local/bin/fs-entrypoint.sh:ro
      # Bind-mount runtime data; entrypoint fixes ownership to freeswitch user
      - ./data/recordings:/var/lib/freeswitch/recordings
      - ./data/log:/var/log/freeswitch
      - ./data/lib:/var/lib/freeswitch
    # ports:
    #   - "5060:5060/udp"
    #   - "5060:5060/tcp"
    #   - "5061:5061/tcp"
    #   - "5080:5080/udp"
    #   - "6080:6080/udp"
    #   - "5066:5066/tcp"
    #   - "7443:7443/tcp"
    #   - "16384-16420:16384-16420/udp"
    healthcheck:
      test: ["CMD", "bash", "-lc", "fs_cli -P 8021 -p ClueCon -x 'status' | grep -q UP"]
      interval: 15s
      timeout: 5s
      retries: 20

  mysql:
    image: mysql:8.0
    container_name: fs-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-rootpass}
      - MYSQL_DATABASE=${DB_NAME:-freeswitch}
      - MYSQL_USER=${DB_USER:-fsapp}
      - MYSQL_PASSWORD=${DB_PASSWORD:-fsapp}
      - TZ=${TIMEZONE:-Asia/Ho_Chi_Minh}
    ports:
      - "3306:3306"
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${DB_ROOT_PASSWORD:-rootpass}"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  app-node-modules: {}
  mysql-data: {}
